import React, { useState, useEffect, useMemo } from 'react';
import axios from 'axios';
import { 
  ChevronDown, Plus, Trash2, Save, CheckCircle, Loader2, BookOpen, Layers, Fingerprint, List, Eye
} from 'lucide-react';
import apiBaseUrl from "../../../config/baseurl"; 

const api = axios.create({
  baseURL: apiBaseUrl,
  headers: { 'Content-Type': 'application/json' }
});

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('token'); 
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

const MARKING_SYSTEMS = ['CGPA (10 Point)', 'Percentage (100%)', 'Pass/Fail', 'Credit Based'];

export const Syllabus = () => {
  // ─── VIEW STATE ('list' or 'build') ────────────────────────────────────
  const [viewMode, setViewMode] = useState('list'); 

  // ─── DATA STATE ────────────────────────────────────────────────────────
  const [programs, setPrograms] = useState([]); 
  const [faculty, setFaculty] = useState([]);
  const [savedSyllabuses, setSavedSyllabuses] = useState([]); 
  const [loading, setLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  // ─── SELECTION STATE ───────────────────────────────────────────────────
  const [headerInfo, setHeaderInfo] = useState({
    courseId: '',
    specializationId: '',
    batchId: '',
    status: 'In-Progress'
  });

  const [activeSem, setActiveSem] = useState(1);
  const [subjects, setSubjects] = useState({ 1: [] });

  // ─── AUTO-GENERATE SYLLABUS CODE ───────────────────────────────────────
  const autoGeneratedCode = useMemo(() => {
    const course = programs.find(p => p.id == headerInfo.courseId);
    if (!course) return '';
    
    const spec = course.specializations?.find(s => s.id == headerInfo.specializationId);
    const batch = course.batches?.find(b => b.id == headerInfo.batchId);
    
    const cPart = course.name.split(' ')[0].toUpperCase();
    const sPart = spec ? spec.name.split(' ')[0].toUpperCase() : 'GEN';
    const bPart = batch ? batch.name.replace(/\s+/g, '') : '202X';
    
    return `${cPart}-${sPart}-${bPart}-S${activeSem}`;
  }, [headerInfo, activeSem, programs]);

  // ─── TOTALS CALCULATOR ─────────────────────────────────────────────────
  const { subTotals, grandTotal } = useMemo(() => {
    const currentSubs = subjects[activeSem] || [];
    const totals = currentSubs.reduce((acc, curr) => {
      acc.internal += parseInt(curr.internal) || 0;
      acc.university += parseInt(curr.university) || 0;
      acc.laboratory += parseInt(curr.laboratory) || 0;
      acc.presentation += parseInt(curr.presentation) || 0;
      return acc;
    }, { internal: 0, university: 0, laboratory: 0, presentation: 0 });

    const grand = totals.internal + totals.university + totals.laboratory + totals.presentation;
    return { subTotals: totals, grandTotal: grand };
  }, [subjects, activeSem]);

  // ─── INITIAL LOAD (Fetch Programs, Faculty, & Saved Syllabuses) ────────
  const fetchData = async () => {
    try {
      setLoading(true);
      const [progRes, facultyRes, syllabusRes] = await Promise.all([
        api.get('/admin/programs'),
        api.get('/admin/employees/list'),
        api.get('/admin/syllabus') // Fetching the saved list
      ]);
      setPrograms(progRes.data?.data || []);
      setFaculty(facultyRes.data?.data || []);
      setSavedSyllabuses(syllabusRes.data?.data || []);
    } catch (error) {
      console.error("Fetch failed:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  // ─── DYNAMIC DERIVED DATA ──────────────────────────────────────────────
  const selectedCourse = useMemo(() => programs.find(p => p.id == headerInfo.courseId), [programs, headerInfo.courseId]);
  const filteredSpecs = useMemo(() => selectedCourse?.specializations || [], [selectedCourse]);
  const filteredBatches = useMemo(() => {
    if (!selectedCourse || !headerInfo.specializationId) return [];
    const specName = filteredSpecs.find(s => s.id == headerInfo.specializationId)?.name;
    return (selectedCourse.batches || []).filter(batch => !specName || (batch.specs || []).includes(specName));
  }, [selectedCourse, headerInfo.specializationId, filteredSpecs]);

  const semesterTabs = Array.from({ length: selectedCourse?.semesters || 0 }, (_, i) => i + 1);

  // ─── HANDLERS ──────────────────────────────────────────────────────────
  const handleCourseChange = (id) => {
    setHeaderInfo({ courseId: id, specializationId: '', batchId: '', status: 'In-Progress' });
    setActiveSem(1);
    setSubjects({ 1: [] });
  };

  const handleAddSubjectRow = () => {
    const newSub = { id: Date.now(), name: '', code: '', faculty: '', markingSystem: 'Percentage (100%)', internal: '', university: '', laboratory: '', presentation: '', elective: false };
    setSubjects(prev => ({ ...prev, [activeSem]: [...(prev[activeSem] || []), newSub] }));
  };

  const handleSubjectChange = (id, field, value) => {
    setSubjects(prev => ({
      ...prev,
      [activeSem]: prev[activeSem].map(sub => (sub.id === id ? { ...sub, [field]: value } : sub))
    }));
  };

  const handleSaveSyllabus = async () => {
    if (!headerInfo.batchId) return alert("Please select Course, Specialization, and Batch.");
    
    try {
      setIsSaving(true);
      // 🚀 FIXED: using snake_case payload to prevent 400 Bad Request
      const payload = { 
        course_id: headerInfo.courseId,
        specialization_id: headerInfo.specializationId,
        batch_id: headerInfo.batchId,
        status: headerInfo.status,
        semester_number: activeSem,
        syllabus_code: autoGeneratedCode,
        subjects: subjects[activeSem] || []
      };

      const res = await api.post('/admin/syllabus', payload);
      if (res.data.success) {
        alert(`Syllabus Saved Successfully!`);
        await fetchData(); // Refresh the list
        setViewMode('list'); // Switch back to the list view
        // Reset form
        setHeaderInfo({ courseId: '', specializationId: '', batchId: '', status: 'In-Progress' });
        setSubjects({ 1: [] });
      }
    } catch (err) {
      console.error("Save Error:", err.response?.data);
      alert(err.response?.data?.message || "Failed to save syllabus.");
    } finally { setIsSaving(false); }
  };

  const handleDeleteSyllabus = async (id) => {
    if(!window.confirm("Are you sure you want to delete this syllabus?")) return;
    try {
      await api.delete(`/admin/syllabus/${id}`);
      fetchData(); // Refresh list
    } catch (err) {
      alert("Failed to delete syllabus.");
    }
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center bg-slate-50"><Loader2 className="animate-spin text-blue-600" size={40} /></div>;

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8 font-sans text-left">
      <div className="max-w-[1400px] mx-auto space-y-6">
        
        {/* ── HEADER & TOGGLE BUTTON ── */}
        <header className="flex justify-between items-center bg-white p-4 rounded-2xl border border-gray-200 shadow-sm">
          <div>
            <h1 className="text-xl font-black text-slate-900 tracking-tight">Syllabus Management</h1>
            <p className="text-xs text-slate-500 font-medium">Manage and build academic structures.</p>
          </div>
          
          {viewMode === 'list' ? (
            <button onClick={() => setViewMode('build')} className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 transition-all shadow-md shadow-blue-100">
              <Plus size={16} strokeWidth={3}/> Build New Syllabus
            </button>
          ) : (
            <button onClick={() => setViewMode('list')} className="bg-slate-100 hover:bg-slate-200 text-slate-700 px-5 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 transition-all">
              <List size={16} strokeWidth={3}/> Back to List
            </button>
          )}
        </header>

        {/* ══════════════════════════════════════════════════════════════════════ */}
        {/* 👁️ LIST VIEW MODE                                                      */}
        {/* ══════════════════════════════════════════════════════════════════════ */}
        {viewMode === 'list' && (
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead className="bg-slate-50/80 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-gray-100">
                  <tr>
                    <th className="px-6 py-4">Syllabus Code</th>
                    <th className="px-4 py-4">Course Details</th>
                    <th className="px-4 py-4">Batch</th>
                    <th className="px-4 py-4 text-center">Semester</th>
                    <th className="px-4 py-4 text-center">Status</th>
                    <th className="px-6 py-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {savedSyllabuses.length === 0 ? (
                    <tr>
                      <td colSpan="6" className="px-6 py-16 text-center">
                        <div className="flex flex-col items-center gap-2">
                          <BookOpen size={32} className="text-slate-300" />
                          <p className="text-slate-400 text-sm font-bold">No syllabuses found.</p>
                          <button onClick={() => setViewMode('build')} className="text-blue-600 font-bold text-xs hover:underline mt-2">Create your first syllabus</button>
                        </div>
                      </td>
                    </tr>
                  ) : (
                    savedSyllabuses.map((syllabus) => (
                      <tr key={syllabus.id} className="hover:bg-slate-50 transition-colors">
                        <td className="px-6 py-4">
                          <span className="px-3 py-1 bg-blue-50 text-blue-700 text-xs font-black rounded-lg uppercase tracking-wider border border-blue-100">
                            {syllabus.syllabus_code || 'N/A'}
                          </span>
                        </td>
                        <td className="px-4 py-4">
                          <p className="text-sm font-bold text-gray-800">{syllabus.course_name || 'Course'}</p>
                          <p className="text-[10px] font-bold text-gray-400 uppercase">{syllabus.specialization_name || 'General'}</p>
                        </td>
                        <td className="px-4 py-4 text-sm font-bold text-slate-600">{syllabus.batch_name || '—'}</td>
                        <td className="px-4 py-4 text-center text-sm font-black text-slate-700">Sem {syllabus.semester_number || '-'}</td>
                        <td className="px-4 py-4 text-center">
                          <span className={`px-2 py-1 text-[10px] font-black rounded uppercase tracking-wider ${syllabus.status === 'Finalized' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
                            {syllabus.status || 'In-Progress'}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-right">
                          <button className="p-2 text-gray-400 hover:text-blue-600 transition-colors" title="View/Edit"><Eye size={16} /></button>
                          <button onClick={() => handleDeleteSyllabus(syllabus.id)} className="p-2 text-gray-400 hover:text-red-500 transition-colors" title="Delete"><Trash2 size={16} /></button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* ══════════════════════════════════════════════════════════════════════ */}
        {/* 🛠️ BUILD VIEW MODE                                                     */}
        {/* ══════════════════════════════════════════════════════════════════════ */}
        {viewMode === 'build' && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* ── SELECTION CARD ── */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 relative">
              {autoGeneratedCode && (
                <div className="absolute -top-3 left-6 flex items-center gap-2 bg-blue-600 text-white px-4 py-1 rounded-full shadow-md">
                  <Fingerprint size={12} />
                  <span className="text-[10px] font-black tracking-widest">{autoGeneratedCode}</span>
                </div>
              )}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-2">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Course</label>
                  <select value={headerInfo.courseId} onChange={e => handleCourseChange(e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                    <option value="">Select Course...</option>
                    {programs.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Specialization</label>
                  <select disabled={!headerInfo.courseId} value={headerInfo.specializationId} onChange={e => setHeaderInfo({...headerInfo, specializationId: e.target.value, batchId: ''})} className="w-full disabled:opacity-50 bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                    <option value="">Select Specialization...</option>
                    {filteredSpecs.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Batch</label>
                  <select disabled={!headerInfo.specializationId} value={headerInfo.batchId} onChange={e => setHeaderInfo({...headerInfo, batchId: e.target.value})} className="w-full disabled:opacity-50 bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                    <option value="">Select Batch...</option>
                    {filteredBatches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
                  </select>
                </div>
              </div>
            </div>

            {/* ── SEMESTER TABS ── */}
            {headerInfo.courseId && (
              <div className="flex items-center gap-2 overflow-x-auto pb-2">
                {semesterTabs.map(sem => (
                  <button key={sem} onClick={() => setActiveSem(sem)} className={`px-6 py-2 rounded-xl text-xs font-black border transition-all ${activeSem === sem ? 'bg-blue-600 border-blue-600 text-white shadow-md' : 'bg-white border-gray-200 text-slate-500 hover:bg-slate-50'}`}>
                    SEM {sem}
                  </button>
                ))}
              </div>
            )}

            {/* ── SUBJECT TABLE ── */}
            {headerInfo.batchId && (
              <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-100 bg-slate-50/50 flex justify-between items-center">
                  <h2 className="text-sm font-bold text-gray-800 uppercase tracking-wider flex items-center gap-2"><BookOpen size={16} className="text-blue-600"/> Subjects for Sem {activeSem}</h2>
                  <button onClick={handleAddSubjectRow} className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-xs font-black flex items-center gap-2 transition-all shadow-md shadow-blue-100"><Plus size={14} strokeWidth={3} /> ADD SUBJECT</button>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse min-w-[1200px]">
                    <thead>
                      <tr className="bg-slate-50/50 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-gray-100">
                        <th className="px-6 py-4 w-[20%]">Subject Name</th>
                        <th className="px-3 py-4 w-[10%]">Code</th>
                        <th className="px-3 py-4 w-[15%]">Faculty</th>
                        <th className="px-3 py-4 w-[15%]">Marking System</th>
                        <th className="px-2 py-4 text-center w-[8%]">Int</th>
                        <th className="px-2 py-4 text-center w-[8%]">Uni</th>
                        <th className="px-2 py-4 text-center w-[8%]">Lab</th>
                        <th className="px-2 py-4 text-center w-[8%]">Pres</th>
                        <th className="px-2 py-4 text-center w-[6%]">Elec</th>
                        <th className="px-4 py-4 w-[5%]"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {(subjects[activeSem] || []).map((sub) => (
                        <tr key={sub.id} className="hover:bg-blue-50/10 transition-colors">
                          <td className="px-6 py-3"><input type="text" value={sub.name} onChange={e => handleSubjectChange(sub.id, 'name', e.target.value)} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-700 outline-none focus:border-blue-500" placeholder="Subject name..." /></td>
                          <td className="px-2 py-3"><input type="text" value={sub.code} onChange={e => handleSubjectChange(sub.id, 'code', e.target.value)} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-xs font-black text-blue-600 uppercase outline-none focus:border-blue-500" placeholder="CODE" /></td>
                          <td className="px-2 py-3">
                            <select value={sub.faculty} onChange={e => handleSubjectChange(sub.id, 'faculty', e.target.value)} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-600 outline-none">
                              <option value="">Unassigned</option>
                              {faculty.map(f => <option key={f.id} value={f.firstName}>{f.firstName} {f.lastName}</option>)}
                            </select>
                          </td>
                          <td className="px-2 py-3">
                            <select value={sub.markingSystem} onChange={e => handleSubjectChange(sub.id, 'markingSystem', e.target.value)} className="w-full bg-white border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-600 outline-none cursor-pointer">
                              {MARKING_SYSTEMS.map(m => <option key={m} value={m}>{m}</option>)}
                            </select>
                          </td>
                          <td className="px-2 py-3"><input type="number" value={sub.internal} onChange={e => handleSubjectChange(sub.id, 'internal', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:border-blue-500" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.university} onChange={e => handleSubjectChange(sub.id, 'university', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:border-blue-500" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.laboratory} onChange={e => handleSubjectChange(sub.id, 'laboratory', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:border-blue-500" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.presentation} onChange={e => handleSubjectChange(sub.id, 'presentation', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:border-blue-500" /></td>
                          <td className="px-2 py-3 text-center"><input type="checkbox" checked={sub.elective} onChange={e => handleSubjectChange(sub.id, 'elective', e.target.checked)} className="w-4 h-4 rounded border-gray-300 text-blue-600" /></td>
                          <td className="px-4 py-3 text-right">
                            <button onClick={() => setSubjects(p => ({...p, [activeSem]: p[activeSem].filter(s => s.id !== sub.id)}))} className="text-red-300 hover:text-red-500 transition-colors"><Trash2 size={16} /></button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    
                    {/* ── TOTALS FOOTER ── */}
                    {((subjects[activeSem] || []).length > 0) && (
                      <tfoot className="bg-slate-50/80 border-t border-gray-200">
                        <tr className="border-b border-gray-100">
                          <td colSpan="4" className="px-6 py-4 text-xs font-black text-slate-500 text-right uppercase tracking-wider">Semester Sub-Total</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.internal > 0 ? subTotals.internal : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.university > 0 ? subTotals.university : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.laboratory > 0 ? subTotals.laboratory : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.presentation > 0 ? subTotals.presentation : '-'}</td>
                          <td colSpan="2"></td>
                        </tr>
                        <tr className="bg-white">
                          <td colSpan="4" className="px-6 py-6 text-sm font-black text-blue-900 text-right uppercase tracking-tighter">Total Semester Marks (All Categories)</td>
                          <td colSpan="4" className="px-1 py-6 text-xl font-black text-blue-600 text-center">
                            <span className="bg-blue-50 px-6 py-2 rounded-lg border border-blue-100">{grandTotal > 0 ? grandTotal : '0'}</span>
                          </td>
                          <td colSpan="2"></td>
                        </tr>
                      </tfoot>
                    )}
                  </table>
                  {(subjects[activeSem] || []).length === 0 && <div className="py-16 text-center text-slate-400 italic text-xs font-bold">Add subjects to start building.</div>}
                </div>
              </div>
            )}

            {/* ── FOOTER ACTIONS ── */}
            <div className="flex justify-end pt-4 border-t border-gray-200 gap-4">
                <button onClick={() => setViewMode('list')} className="px-8 py-3 bg-white border border-gray-300 text-slate-600 font-black text-xs rounded-xl hover:bg-slate-50 transition-all uppercase tracking-widest">Discard</button>
                <button disabled={isSaving || !headerInfo.batchId} onClick={handleSaveSyllabus} className="px-8 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-black text-xs rounded-xl shadow-xl shadow-blue-200 transition-all uppercase tracking-widest flex items-center gap-2">
                  {isSaving ? <Loader2 className="animate-spin" size={16}/> : <Save size={16}/>}
                  Review & Publish
                </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default Syllabus;