import React, { useState, useEffect, useMemo } from 'react';
import axios from 'axios';
import { 
  ChevronDown, Plus, Trash2, Save, Loader2, BookOpen, 
  Fingerprint, List, Eye, Edit, Upload
} from 'lucide-react';
import apiBaseUrl from "../../../config/baseurl"; 

const api = axios.create({
  baseURL: apiBaseUrl,
});

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('token'); 
  if (token) config.headers.Authorization = `Bearer ${token}`;
  return config;
});

const MARKING_SYSTEMS = ['CGPA (10 Point)', 'Percentage (100%)', 'Pass/Fail', 'Credit Based'];

export const Syllabus = () => {
  const [viewMode, setViewMode] = useState('list'); 
  const [editingId, setEditingId] = useState(null);

  const [programs, setPrograms] = useState([]); 
  const [faculty, setFaculty] = useState([]);
  const [savedSyllabuses, setSavedSyllabuses] = useState([]); 
  const [subjectMaster, setSubjectMaster] = useState([]); 
  const [loading, setLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const [headerInfo, setHeaderInfo] = useState({
    courseId: '',
    specializationId: '',
    batchId: '',
    status: 'In-Progress'
  });

  const [activeSem, setActiveSem] = useState(1);
  const [semesterCount, setSemesterCount] = useState(1);
  const [subjects, setSubjects] = useState({ 1: [] });
  const [semesterFiles, setSemesterFiles] = useState({}); 
  const [copySource, setCopySource] = useState(''); 

  const fetchData = async () => {
    try {
      setLoading(true);
      const [progRes, facultyRes, syllabusRes, formRes] = await Promise.all([
        api.get('/admin/programs'),
        api.get('/admin/employees/list'),
        api.get('/admin/syllabus'),
        api.get('/admin/syllabus/form-data') 
      ]);
      setPrograms(progRes.data?.data || []);
      setFaculty(facultyRes.data?.data || []);
      setSavedSyllabuses(syllabusRes.data?.data || []);
      setSubjectMaster(formRes.data?.data?.subjectMaster || []);
    } catch (error) {
      console.error("Fetch failed:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const selectedCourse = useMemo(() => programs.find(p => p.id == headerInfo.courseId), [programs, headerInfo.courseId]);
  const filteredSpecs = useMemo(() => selectedCourse?.specializations || [], [selectedCourse]);
  const selectedSpec = useMemo(() => filteredSpecs.find(s => s.id == headerInfo.specializationId), [filteredSpecs, headerInfo.specializationId]);
  
  const filteredBatches = useMemo(() => {
    if (!selectedCourse || !headerInfo.specializationId) return [];
    const specName = selectedSpec?.name;
    return (selectedCourse.batches || []).filter(batch => 
      !specName || 
      (batch.specs || []).includes(specName) || 
      batch.specialization_id == headerInfo.specializationId
    );
  }, [selectedCourse, selectedSpec, headerInfo.specializationId]);

  useEffect(() => {
    if (!editingId && (selectedSpec || selectedCourse)) {
      const count = selectedSpec?.semesters || selectedCourse?.semesters || 1;
      setSemesterCount(count);
    }
  }, [selectedSpec, selectedCourse, editingId]);

  const semesterTabs = Array.from({ length: semesterCount }, (_, i) => i + 1);

  const autoGeneratedCode = useMemo(() => {
    if (!selectedCourse) return '';
    const batch = selectedCourse.batches?.find(b => b.id == headerInfo.batchId);
    const cPart = selectedCourse.name.split(' ')[0].toUpperCase();
    const sPart = selectedSpec ? selectedSpec.name.split(' ')[0].toUpperCase() : 'GEN';
    const bPart = batch ? batch.name.replace(/\s+/g, '') : '202X';
    return `${cPart}-${sPart}-${bPart}-S${activeSem}`;
  }, [headerInfo, activeSem, selectedCourse, selectedSpec]);

  const { subTotals, grandTotal } = useMemo(() => {
    const currentSubs = subjects[activeSem] || [];
    const totals = currentSubs.reduce((acc, curr) => {
      acc.internal += parseInt(curr.internal) || 0;
      acc.university += parseInt(curr.university) || 0;
      acc.laboratory += parseInt(curr.laboratory) || 0;
      acc.presentation += parseInt(curr.presentation) || 0;
      return acc;
    }, { internal: 0, university: 0, laboratory: 0, presentation: 0 });

    const grand = totals.internal + totals.university + totals.laboratory + totals.presentation;
    return { subTotals: totals, grandTotal: grand };
  }, [subjects, activeSem]);

  const handleCourseChange = (id) => {
    setHeaderInfo({ courseId: id, specializationId: '', batchId: '', status: 'In-Progress' });
    setActiveSem(1);
    setSubjects({ 1: [] });
    setSemesterFiles({});
  };

  const handleSpecChange = (id) => {
    setHeaderInfo(prev => ({ ...prev, specializationId: id, batchId: '' }));
    setActiveSem(1);
  };

  const handleAddSemester = () => setSemesterCount(prev => prev + 1);

  // 🚀 FIXED: Auto-Generate Subject Code when adding a row
  const handleAddSubjectRow = () => {
    const currentIndex = subjects[activeSem]?.length || 0;
    
    // Create a prefix from the course name (e.g., "B tech" -> "BTE")
    let cPrefix = 'SUB';
    if (selectedCourse && selectedCourse.name) {
       cPrefix = selectedCourse.name.replace(/[^a-zA-Z]/g, '').substring(0, 3).toUpperCase();
    }
    
    // Auto generated string like BTE-S1-01
    const generatedSubjectCode = `${cPrefix}-S${activeSem}-${(currentIndex + 1).toString().padStart(2, '0')}`;

    const newSub = { 
      id: Date.now(), 
      name: '', 
      code: generatedSubjectCode, // Pre-filled dynamically!
      faculty: '', 
      markingSystem: 'Percentage (100%)', 
      internal: '', 
      university: '', 
      laboratory: '', 
      presentation: '', 
      elective: false 
    };
    
    setSubjects(prev => ({ ...prev, [activeSem]: [...(prev[activeSem] || []), newSub] }));
  };

  const handleSubjectChange = (id, field, value) => {
    setSubjects(prev => ({
      ...prev,
      [activeSem]: prev[activeSem].map(sub => (sub.id === id ? { ...sub, [field]: value } : sub))
    }));
  };

  const handleSubjectNameChange = (id, newName) => {
    const matchedSubject = subjectMaster.find(sm => sm.name.toLowerCase() === newName.toLowerCase());
    setSubjects(prev => ({
      ...prev,
      [activeSem]: prev[activeSem].map(sub => {
        if (sub.id === id) {
          return {
            ...sub,
            name: newName,
            // If it matches a DB subject, auto-fill the code! Otherwise leave whatever was there.
            code: matchedSubject ? matchedSubject.code : sub.code 
          };
        }
        return sub;
      })
    }));
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) setSemesterFiles(prev => ({ ...prev, [activeSem]: file }));
  };

  const handleCopySyllabus = async () => {
    if (!copySource) return alert("Please select a syllabus to copy from.");
    try {
      setLoading(true);
      const [c, s, b] = copySource.split('|');
      const res = await api.get('/admin/syllabus', { params: { course: c, specialization: s, batch: b } });
      const fullSubjects = res.data.data;
      
      const groupedSubjects = {};
      let maxSem = 1;

      fullSubjects.forEach(sub => {
        const sem = sub.semester;
        if (sem > maxSem) maxSem = sem;
        if (!groupedSubjects[sem]) groupedSubjects[sem] = [];
        
        groupedSubjects[sem].push({
          id: Date.now() + Math.random(), 
          name: sub.subject_name,
          code: sub.subject_code,
          faculty: sub.faculty_name !== 'Unassigned' ? sub.faculty_name : '',
          markingSystem: sub.marking_system,
          internal: sub.int_marks,
          university: sub.uni_marks,
          laboratory: sub.lab_marks,
          presentation: sub.pres_marks,
          elective: sub.is_elective === 1
        });
      });

      setSubjects(groupedSubjects);
      setSemesterCount(Math.max(maxSem, semesterCount));
      alert("Syllabus copied successfully! You can now modify and save it.");
    } catch (error) {
      console.error("Failed to copy:", error);
      alert("Failed to copy syllabus.");
    } finally {
      setLoading(false);
    }
  };

  const handleEditSyllabus = async (syllabusSummary) => {
    try {
      setLoading(true);
      const res = await api.get('/admin/syllabus', {
        params: { course: syllabusSummary.course_name, specialization: syllabusSummary.specialization_name, batch: syllabusSummary.batch_name }
      });
      const fullSubjects = res.data.data; 

      const course = programs.find(p => p.name === syllabusSummary.course_name);
      const courseId = course ? course.id : '';
      const spec = course?.specializations?.find(s => s.name === syllabusSummary.specialization_name);
      const specializationId = spec ? spec.id : '';
      const batch = course?.batches?.find(b => b.name === syllabusSummary.batch_name);
      const batchId = batch ? batch.id : '';

      setHeaderInfo({ courseId, specializationId, batchId, status: syllabusSummary.status || 'In-Progress' });

      const groupedSubjects = {};
      let maxSem = 1;

      fullSubjects.forEach(sub => {
        const sem = sub.semester;
        if (sem > maxSem) maxSem = sem;
        if (!groupedSubjects[sem]) groupedSubjects[sem] = [];
        
        groupedSubjects[sem].push({
          id: sub.id,
          name: sub.subject_name,
          code: sub.subject_code, // Will populate the exact generated code from DB!
          faculty: sub.faculty_name !== 'Unassigned' ? sub.faculty_name : '',
          markingSystem: sub.marking_system,
          internal: sub.int_marks,
          university: sub.uni_marks,
          laboratory: sub.lab_marks,
          presentation: sub.pres_marks,
          elective: sub.is_elective === 1
        });
      });

      setSubjects(groupedSubjects);
      setActiveSem(1);
      setSemesterCount(Math.max(maxSem, 1));
      setEditingId(syllabusSummary.id || syllabusSummary.syllabus_code);
      setViewMode('build');

    } catch (error) {
      console.error("Failed to load syllabus details:", error);
      alert("Failed to load syllabus details.");
    } finally {
      setLoading(false);
    }
  };

  const handleSaveSyllabus = async () => {
    if (!headerInfo.batchId) return alert("Please select Course, Specialization, and Batch.");
    try {
      setIsSaving(true);
      const formData = new FormData();
      formData.append('course_id', headerInfo.courseId);
      formData.append('specialization_id', headerInfo.specializationId);
      formData.append('batch_id', headerInfo.batchId);
      formData.append('status', headerInfo.status);
      formData.append('semester_number', activeSem);
      formData.append('syllabus_code', autoGeneratedCode);
      formData.append('subjects', JSON.stringify(subjects[activeSem] || []));
      
      if (semesterFiles[activeSem]) formData.append('syllabus_file', semesterFiles[activeSem]);

      if (editingId) {
        const res = await api.put(`/admin/syllabus/${editingId}`, formData);
        if (res.data.success) alert(`Syllabus Updated Successfully!`);
      } else {
        const res = await api.post('/admin/syllabus', formData);
        if (res.data.success) alert(`Syllabus Saved Successfully!`);
      }

      await fetchData(); 
      handleCancelBuild(); 
    } catch (err) {
      console.error("Save Error:", err.response?.data);
      alert(err.response?.data?.message || "Failed to save syllabus.");
    } finally { 
      setIsSaving(false); 
    }
  };

  const handleDeleteSyllabus = async (syllabusCode) => {
    if(!window.confirm("Are you sure you want to delete this entire syllabus?")) return;
    try {
      await api.delete(`/admin/syllabus/${syllabusCode}`); 
      fetchData(); 
    } catch (err) {
      alert("Failed to delete syllabus.");
    }
  };

  const handleCancelBuild = () => {
    setViewMode('list');
    setEditingId(null);
    setHeaderInfo({ courseId: '', specializationId: '', batchId: '', status: 'In-Progress' });
    setSubjects({ 1: [] });
    setSemesterFiles({});
    setActiveSem(1);
    setCopySource('');
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center bg-slate-50"><Loader2 className="animate-spin text-blue-600" size={40} /></div>;

  return (
    <div className="min-h-screen bg-slate-50 p-4 md:p-8 font-sans text-left">
      <div className="max-w-[1400px] mx-auto space-y-6">
        
        {/* ── HEADER & TOGGLE BUTTON ── */}
        <header className="flex justify-between items-center bg-white p-4 rounded-2xl border border-gray-200 shadow-sm">
          <div>
            <h1 className="text-xl font-black text-slate-900 tracking-tight">Syllabus Management</h1>
            <p className="text-xs text-slate-500 font-medium">Manage and build academic structures.</p>
          </div>
          
          {viewMode === 'list' ? (
            <button onClick={() => { setViewMode('build'); setEditingId(null); }} className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 transition-all shadow-md shadow-blue-100">
              <Plus size={16} strokeWidth={3}/> Build New Syllabus
            </button>
          ) : (
            <button onClick={handleCancelBuild} className="bg-slate-100 hover:bg-slate-200 text-slate-700 px-5 py-2.5 rounded-xl text-sm font-bold flex items-center gap-2 transition-all">
              <List size={16} strokeWidth={3}/> Back to List
            </button>
          )}
        </header>

        {/* ══════════════════════════════════════════════════════════════════════ */}
        {/* 👁️ LIST VIEW MODE                                                      */}
        {/* ══════════════════════════════════════════════════════════════════════ */}
        {viewMode === 'list' && (
          <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead className="bg-slate-50/80 text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-gray-100">
                  <tr>
                    <th className="px-6 py-4">Syllabus Code</th>
                    <th className="px-4 py-4">Course Details</th>
                    <th className="px-4 py-4">Batch</th>
                    <th className="px-4 py-4 text-center">Semesters</th>
                    <th className="px-4 py-4 text-center">Status</th>
                    <th className="px-6 py-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {savedSyllabuses.length === 0 ? (
                    <tr>
                      <td colSpan="6" className="px-6 py-16 text-center">
                        <div className="flex flex-col items-center gap-2">
                          <BookOpen size={32} className="text-slate-300" />
                          <p className="text-slate-400 text-sm font-bold">No syllabuses found.</p>
                          <button onClick={() => { setViewMode('build'); setEditingId(null); }} className="text-blue-600 font-bold text-xs hover:underline mt-2">Create your first syllabus</button>
                        </div>
                      </td>
                    </tr>
                  ) : (
                    savedSyllabuses.map((syllabus) => (
                      <tr key={syllabus.id} className="hover:bg-slate-50 transition-colors">
                        <td className="px-6 py-4">
                          <span className="px-3 py-1 bg-blue-50 text-blue-700 text-xs font-black rounded-lg uppercase tracking-wider border border-blue-100">
                            {syllabus.syllabus_code || 'CURRICULUM'}
                          </span>
                        </td>
                        <td className="px-4 py-4">
                          <p className="text-sm font-bold text-gray-800">{syllabus.course_name || 'Course'}</p>
                          <p className="text-[10px] font-bold text-gray-400 uppercase">{syllabus.specialization_name || 'General'}</p>
                        </td>
                        <td className="px-4 py-4 text-sm font-bold text-slate-600">{syllabus.batch_name || '—'}</td>
                        <td className="px-4 py-4 text-center text-sm font-black text-slate-700">Sem {syllabus.semester_number || '-'}</td>
                        <td className="px-4 py-4 text-center">
                          <span className={`px-2 py-1 text-[10px] font-black rounded uppercase tracking-wider ${syllabus.status === 'Completed' || syllabus.status === 'Finalized' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
                            {syllabus.status || 'In-Progress'}
                          </span>
                        </td>
                        <td className="px-6 py-4 text-right">
                          <button onClick={() => handleEditSyllabus(syllabus)} className="p-2 text-gray-400 hover:text-blue-500 transition-colors" title="View Syllabus"><Eye size={16} /></button>
                          <button onClick={() => handleEditSyllabus(syllabus)} className="p-2 text-gray-400 hover:text-orange-500 transition-colors" title="Edit Syllabus"><Edit size={16} /></button>
                          <button onClick={() => handleDeleteSyllabus(syllabus.syllabus_code)} className="p-2 text-gray-400 hover:text-red-500 transition-colors" title="Delete"><Trash2 size={16} /></button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* ══════════════════════════════════════════════════════════════════════ */}
        {/* 🛠️ BUILD VIEW MODE                                                      */}
        {/* ══════════════════════════════════════════════════════════════════════ */}
        {viewMode === 'build' && (
          <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            
            <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 relative">
              <h2 className="text-sm font-bold text-slate-800 mb-4">1. Select Course / Specialization / Batch</h2>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Course</label>
                  <div className="relative">
                    <select value={headerInfo.courseId} onChange={e => handleCourseChange(e.target.value)} className="w-full appearance-none bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                      <option value="">Select Course...</option>
                      {programs.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                    </select>
                    <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Specialization</label>
                  <div className="relative">
                    <select disabled={!headerInfo.courseId} value={headerInfo.specializationId} onChange={e => handleSpecChange(e.target.value)} className="w-full appearance-none disabled:opacity-50 bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                      <option value="">Select Specialization...</option>
                      {filteredSpecs.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                    </select>
                    <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-[10px] font-black text-slate-400 uppercase">Batch</label>
                  <div className="relative">
                    <select disabled={!headerInfo.specializationId} value={headerInfo.batchId} onChange={e => setHeaderInfo({...headerInfo, batchId: e.target.value})} className="w-full appearance-none disabled:opacity-50 bg-slate-50 border border-gray-200 rounded-xl px-4 py-2.5 text-sm font-bold text-slate-700 outline-none focus:border-blue-500">
                      <option value="">Select Batch...</option>
                      {filteredBatches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
                    </select>
                    <ChevronDown size={14} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-amber-50/50 border border-amber-200 rounded-xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
              <div className="flex items-center gap-3 w-full md:w-auto">
                <span className="text-xs font-bold text-amber-800">Copy syllabus from:</span>
                <div className="relative flex-1 md:w-64">
                  <select value={copySource} onChange={(e) => setCopySource(e.target.value)} className="w-full appearance-none bg-white border border-amber-200 rounded-lg px-3 py-1.5 text-xs font-bold text-slate-700 outline-none focus:border-amber-400">
                    <option value="">Select source...</option>
                    {savedSyllabuses.map(s => (
                      <option key={s.id} value={`${s.course_name}|${s.specialization_name}|${s.batch_name}`}>
                        {s.course_name} - {s.specialization_name} ({s.batch_name})
                      </option>
                    ))}
                  </select>
                  <ChevronDown size={14} className="absolute right-2 top-1/2 -translate-y-1/2 text-amber-600 pointer-events-none" />
                </div>
              </div>
              <button onClick={handleCopySyllabus} className="bg-white border border-amber-300 text-amber-700 px-4 py-1.5 rounded-lg text-xs font-black shadow-sm hover:bg-amber-100 transition-colors w-full md:w-auto">
                Copy All Semesters
              </button>
            </div>

            {headerInfo.specializationId && (
              <div className="flex items-center gap-2 overflow-x-auto pb-2 border-b border-gray-200">
                {semesterTabs.map(sem => (
                  <button 
                    key={sem} 
                    onClick={() => setActiveSem(sem)} 
                    className={`px-5 py-2.5 rounded-t-xl text-xs font-black transition-all ${
                      activeSem === sem 
                        ? 'bg-blue-600 text-white shadow-md' 
                        : 'bg-white border border-b-0 border-gray-200 text-slate-500 hover:bg-slate-50 mt-1'
                    }`}
                  >
                    Sem {sem}
                  </button>
                ))}
                <button 
                  onClick={handleAddSemester} 
                  className="px-4 py-2.5 mt-1 rounded-t-xl text-xs font-black bg-white border border-b-0 border-gray-200 text-blue-600 hover:bg-blue-50 flex items-center gap-1 transition-all"
                >
                  <Plus size={14} strokeWidth={3} /> Add Semester
                </button>
              </div>
            )}

            {/* ── 🚀 INVISIBLE DATALIST TO FEED THE SUBJECT DROPDOWN ── */}
            <datalist id="subject-master-list">
              {subjectMaster.map(sm => (
                <option key={sm.id} value={sm.name}>{sm.code}</option>
              ))}
            </datalist>

            {headerInfo.batchId && (
              <div className="bg-white rounded-b-2xl rounded-tr-2xl border border-t-0 border-gray-200 shadow-sm overflow-hidden -mt-6 z-10 relative">
                
                <div className="px-6 py-4 border-b border-gray-100 bg-slate-50 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                  <h2 className="text-sm font-bold text-gray-800 flex items-center gap-2">
                    2. Configure Subjects & Marks for Sem {activeSem}
                  </h2>
                  
                  <div className="flex items-center gap-3 w-full md:w-auto">
                    <div className="relative">
                      <select 
                        value={headerInfo.status} 
                        onChange={e => setHeaderInfo({...headerInfo, status: e.target.value})} 
                        className={`appearance-none bg-white border border-gray-200 rounded-lg px-3 py-1.5 pr-8 text-xs font-black outline-none focus:border-blue-400 ${
                          headerInfo.status === 'Finalized' || headerInfo.status === 'Completed' ? 'text-green-600' : 'text-amber-600'
                        }`}
                      >
                        <option value="In-Progress">In-Progress</option>
                        <option value="Finalized">Finalized</option>
                      </select>
                      <ChevronDown size={12} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                    </div>

                    <label className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 border border-indigo-200 text-indigo-700 rounded-lg text-xs font-black cursor-pointer hover:bg-indigo-100 transition-colors">
                      <Upload size={14} /> 
                      <span className="truncate max-w-[120px]">
                        {semesterFiles[activeSem] ? semesterFiles[activeSem].name : 'Upload File'}
                      </span>
                      <input type="file" className="hidden" onChange={handleFileChange} accept=".pdf,.doc,.docx,.xls,.xlsx" />
                    </label>

                    <button onClick={handleAddSubjectRow} className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded-lg text-xs font-black flex items-center gap-2 transition-all shadow-sm">
                      <Plus size={14} strokeWidth={3} /> Add Subject
                    </button>
                  </div>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse min-w-[1200px]">
                    <thead>
                      <tr className="bg-white text-[10px] font-black text-slate-400 uppercase tracking-widest border-b border-gray-100">
                        <th className="px-6 py-4 w-[20%]">Subject Name</th>
                        <th className="px-3 py-4 w-[10%]">Code</th>
                        <th className="px-3 py-4 w-[15%]">Faculty Assign</th>
                        <th className="px-3 py-4 w-[15%]">Marking System</th>
                        <th className="px-2 py-4 text-center w-[8%]">Int</th>
                        <th className="px-2 py-4 text-center w-[8%]">Uni</th>
                        <th className="px-2 py-4 text-center w-[8%]">Lab</th>
                        <th className="px-2 py-4 text-center w-[8%]">Pres</th>
                        <th className="px-2 py-4 text-center w-[6%]">Elec</th>
                        <th className="px-4 py-4 w-[5%]"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {(subjects[activeSem] || []).map((sub) => (
                        <tr key={sub.id} className="hover:bg-blue-50/10 transition-colors">
                          <td className="px-6 py-3">
                            <input 
                              list="subject-master-list"
                              type="text" 
                              value={sub.name} 
                              onChange={e => handleSubjectNameChange(sub.id, e.target.value)} 
                              className="w-full bg-slate-50 border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-700 outline-none focus:bg-white focus:border-blue-400" 
                              placeholder="Type or select subject..." 
                            />
                          </td>
                          <td className="px-2 py-3">
                            <input 
                              type="text" 
                              value={sub.code} 
                              onChange={e => handleSubjectChange(sub.id, 'code', e.target.value)} 
                              className="w-full bg-slate-50 border border-gray-200 rounded-lg px-3 py-2 text-xs font-black text-slate-700 uppercase outline-none focus:bg-white focus:border-blue-400" 
                              placeholder="CODE" 
                            />
                          </td>
                          <td className="px-2 py-3">
                            <div className="relative">
                              <select value={sub.faculty} onChange={e => handleSubjectChange(sub.id, 'faculty', e.target.value)} className="w-full appearance-none bg-slate-50 border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-600 outline-none focus:bg-white focus:border-blue-400">
                                <option value="">Select Faculty...</option>
                                {faculty.map(f => <option key={f.id} value={f.firstName}>{f.firstName} {f.lastName}</option>)}
                              </select>
                              <ChevronDown size={14} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                            </div>
                          </td>
                          <td className="px-2 py-3">
                            <div className="relative">
                              <select value={sub.markingSystem} onChange={e => handleSubjectChange(sub.id, 'markingSystem', e.target.value)} className="w-full appearance-none bg-slate-50 border border-gray-200 rounded-lg px-3 py-2 text-xs font-bold text-slate-600 outline-none focus:bg-white focus:border-blue-400 cursor-pointer">
                                {MARKING_SYSTEMS.map(m => <option key={m} value={m}>{m}</option>)}
                              </select>
                              <ChevronDown size={14} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
                            </div>
                          </td>
                          <td className="px-2 py-3"><input type="number" value={sub.internal} onChange={e => handleSubjectChange(sub.id, 'internal', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:bg-white focus:border-blue-400" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.university} onChange={e => handleSubjectChange(sub.id, 'university', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:bg-white focus:border-blue-400" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.laboratory} onChange={e => handleSubjectChange(sub.id, 'laboratory', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:bg-white focus:border-blue-400" /></td>
                          <td className="px-2 py-3"><input type="number" value={sub.presentation} onChange={e => handleSubjectChange(sub.id, 'presentation', e.target.value)} className="w-full bg-slate-50 border border-gray-200 rounded-lg py-2 text-center text-xs font-bold outline-none focus:bg-white focus:border-blue-400" /></td>
                          <td className="px-2 py-3 text-center">
                            <input type="checkbox" checked={sub.elective} onChange={e => handleSubjectChange(sub.id, 'elective', e.target.checked)} className="w-4 h-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500 cursor-pointer" />
                          </td>
                          <td className="px-4 py-3 text-right">
                            <button onClick={() => setSubjects(p => ({...p, [activeSem]: p[activeSem].filter(s => s.id !== sub.id)}))} className="p-1.5 bg-red-50 text-red-500 hover:bg-red-100 rounded-lg transition-colors">
                              <Trash2 size={14} />
                            </button>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                    
                    {/* ── TOTALS FOOTER ── */}
                    {((subjects[activeSem] || []).length > 0) && (
                      <tfoot className="bg-slate-50/80 border-t border-gray-200">
                        <tr className="border-b border-gray-100">
                          <td colSpan="4" className="px-6 py-4 text-xs font-black text-slate-500 text-right uppercase tracking-wider">Semester Sub-Total</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.internal > 0 ? subTotals.internal : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.university > 0 ? subTotals.university : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.laboratory > 0 ? subTotals.laboratory : '-'}</td>
                          <td className="px-1 py-4 text-sm font-bold text-gray-800 text-center">{subTotals.presentation > 0 ? subTotals.presentation : '-'}</td>
                          <td colSpan="2"></td>
                        </tr>
                        <tr className="bg-white">
                          <td colSpan="4" className="px-6 py-6 text-sm font-black text-blue-900 text-right uppercase tracking-tighter">Total Semester Marks (All Categories)</td>
                          <td colSpan="4" className="px-1 py-6 text-xl font-black text-blue-600 text-center">
                            <span className="bg-blue-50 px-6 py-2 rounded-lg border border-blue-100">{grandTotal > 0 ? grandTotal : '0'}</span>
                          </td>
                          <td colSpan="2"></td>
                        </tr>
                      </tfoot>
                    )}
                  </table>
                  {(subjects[activeSem] || []).length === 0 && <div className="py-16 text-center text-slate-400 italic text-xs font-bold">Add subjects to start building.</div>}
                </div>
              </div>
            )}

            {/* ── FOOTER ACTIONS ── */}
            <div className="flex justify-end pt-4 border-t border-gray-200 gap-4">
                <button onClick={handleCancelBuild} className="px-8 py-3 bg-white border border-gray-300 text-slate-600 font-black text-xs rounded-xl hover:bg-slate-50 transition-all uppercase tracking-widest">Discard</button>
                <button disabled={isSaving || !headerInfo.batchId} onClick={handleSaveSyllabus} className="px-8 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-black text-xs rounded-xl shadow-xl shadow-blue-200 transition-all uppercase tracking-widest flex items-center gap-2">
                  {isSaving ? <Loader2 className="animate-spin" size={16}/> : <Save size={16}/>}
                  {editingId ? "Update Syllabus" : "Review & Publish"}
                </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default Syllabus;